#!/usr/bin/env bash
#
# StxSaryus's Arch Hyprland Dotfiles — Fully Automatic Installer
#
# Usage:
#   ./install.sh              # Auto install (recommended defaults, one confirm)
#   ./install.sh --auto       # Same, no confirm (CI / reinstall)
#   ./install.sh --interactive  # Choose apps / shortcuts
#   ./install.sh --configs    # Link configs only
#   ./install.sh --help
#
# Official references shown during install:
#   https://archlinux.org/news/nvidia-590-driver-drops-pascal-support-main-packages-switch-to-open-kernel-modules/
#   https://wiki.hypr.land/Configuring/
#   https://wiki.archlinux.org/title/NVIDIA
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

REPO="$(cd "$(dirname "$0")" && pwd)"
HYPR_DEST="$HOME/.config/hypr"
HYPR_CONF="$HYPR_DEST/hyprland.conf"
MODE="auto"
SKIP_CONFIRM=0
SUDO_KEEPALIVE_PID=""

# Defaults, overridable from the environment for scripted installs:
#   TERMINAL_CMD=alacritty KEY_TERMINAL=RETURN ./install.sh --configs
TERMINAL_CMD="${TERMINAL_CMD:-kitty}"
BROWSER_CMD="${BROWSER_CMD:-firefox}"
FILE_MANAGER_CMD="${FILE_MANAGER_CMD:-thunar}"
# Literal tilde on purpose: this string is written into hyprland.conf,
# where Hyprland does the expanding.
# shellcheck disable=SC2088
LAUNCHER_CMD="${LAUNCHER_CMD:-~/.local/share/bin/launcher-toggle.sh}"
KEY_TERMINAL="${KEY_TERMINAL:-T}"
KEY_BROWSER="${KEY_BROWSER:-B}"
KEY_FILE_MANAGER="${KEY_FILE_MANAGER:-E}"
KEY_LAUNCHER="${KEY_LAUNCHER:-SPACE}"
KEY_LOCK="${KEY_LOCK:-L}"

OPT_WAYPAPER=1
OPT_BTOP=1
OPT_GREETD=0
OPT_NWG_LOOK=1
OPT_NVIDIA=1
NVIDIA_DRIVER="none"

info()    { echo -e "${CYAN}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
banner()  {
    echo -e "\n${CYAN}${BOLD}╭────────────────────────────────────────────────────────────────────╮${NC}"
    printf "${CYAN}${BOLD}│  %-66s │${NC}\n" "$1"
    echo -e "${CYAN}${BOLD}╰────────────────────────────────────────────────────────────────────╯${NC}\n"
}
section() { echo -e "\n${BOLD}── $1 ──${NC}"; }

print_official_notices() {
    banner "Official notices (please read)"
    cat <<'EOF'
[1] NVIDIA 590+ / Pascal (GTX 10xx) — Arch Linux News
    https://archlinux.org/news/nvidia-590-driver-drops-pascal-support-main-packages-switch-to-open-kernel-modules/

    "With the update to driver version 590, the NVIDIA driver no longer supports
     Pascal (GTX 10xx) GPUs or older. [...] Users with GTX 10xx series and older
     cards must switch to the legacy proprietary branch:
       • Uninstall nvidia / nvidia-open / nvidia-dkms
       • Install nvidia-580xx-dkms from the AUR"

    This installer detects Pascal/Maxwell GPUs and installs nvidia-580xx-dkms
    automatically. Turing+ (RTX 20xx / GTX 16xx+) uses nvidia-open from repos.

[2] Hyprland config — https://wiki.hypr.land/Configuring/
    Hyprland 0.55+ may generate ~/.config/hypr/hyprland.lua which takes priority
    over hyprland.conf. This installer moves autogenerated .lua aside so your
    rice .conf is used. Also removes deprecated dwindle:pseudotile (0.55).

[3] Waybar icons — official package ttf-jetbrains-mono-nerd (nerd-fonts)
    Waybar CSS expects "JetBrainsMono Nerd Font". Without it icons show as □.

[4] Arch Wiki — NVIDIA — https://wiki.archlinux.org/title/NVIDIA
    Kernel param nvidia_drm.modeset=1 is set for Wayland/Hyprland.

EOF
}

usage() {
    cat <<EOF
Usage: ./install.sh [OPTION]

  (no args)           Auto install with recommended defaults (asks once)
  --auto              Fully non-interactive
  --interactive       Choose terminal, browser, file manager, launcher, shortcuts
  --configs           Link / copy configs only (no packages)
  --packages          Packages + NVIDIA only (no config link)
  --help              Show this help

Quick start:
  git clone https://github.com/StxSaryus/stxsaryus-s-arch-hyprland-dotfiles.git ~/dotfiles
  cd ~/dotfiles && ./install.sh
  sudo reboot
EOF
}

parse_args() {
    case "${1:-}" in
        "") MODE="auto" ;;
        --auto) MODE="auto"; SKIP_CONFIRM=1 ;;
        --interactive) MODE="interactive" ;;
        --configs) MODE="configs" ;;
        --packages) MODE="packages" ;;
        -h|--help) usage; exit 0 ;;
        *) error "Unknown option: $1 (try --help)" ;;
    esac
}

need_sudo() {
    if ! sudo -n true 2>/dev/null; then
        info "sudo password required..."
        sudo -v || error "sudo failed"
    fi
    if [[ -z "$SUDO_KEEPALIVE_PID" ]]; then
        ( while true; do sudo -n true; sleep 50; kill -0 "$$" || exit; done ) 2>/dev/null &
        SUDO_KEEPALIVE_PID=$!
        trap 'kill "$SUDO_KEEPALIVE_PID" 2>/dev/null || true' EXIT
    fi
}

detect_gpu() {
    local gpu_line
    gpu_line="$(lspci -nn 2>/dev/null | grep -iE 'VGA|3D|Display' | grep -i nvidia | head -1 || true)"
    local pci_id=""
    if [[ -n "$gpu_line" ]]; then
        pci_id="$(echo "$gpu_line" | grep -oE '10de:[0-9a-fA-F]+' | cut -d: -f2 | head -1 || true)"
    fi

    NVIDIA_DRIVER="none"
    if [[ -z "$gpu_line" ]]; then
        OPT_NVIDIA=0
        info "No NVIDIA GPU detected — skipping NVIDIA driver"
        return
    fi

    info "NVIDIA GPU: $gpu_line"
    # Pascal = 1bxx/1cxx, Maxwell = 13xx/14xx, Kepler and older = lower
    case "${pci_id,,}" in
        1c*|1b*|1d80|1d81|1d82|14*|13*|12*|11*|0f*|0e*|0c*|0a*|019*)
            NVIDIA_DRIVER="580xx"
            warn "Pascal/older → AUR nvidia-580xx-dkms (Arch News: NVIDIA 590 dropped Pascal)"
            ;;
        *)
            if journalctl -b -k --no-pager 2>/dev/null | grep -q "not supported by open"; then
                NVIDIA_DRIVER="580xx"
                warn "Open module rejected GPU (no GSP) → forcing nvidia-580xx-dkms"
            else
                NVIDIA_DRIVER="open"
                info "Assuming Turing+ → repo nvidia-open"
            fi
            ;;
    esac
}

ensure_yay() {
    export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
    if command -v yay >/dev/null 2>&1; then
        success "yay: $(command -v yay)"
        return
    fi
    section "Installing yay (AUR helper)"
    need_sudo
    sudo pacman -S --needed --noconfirm base-devel git
    local tmp
    tmp="$(mktemp -d)"
    git clone --depth 1 https://aur.archlinux.org/yay-bin.git "$tmp/yay-bin"
    ( cd "$tmp/yay-bin" && makepkg -si --noconfirm )
    rm -rf "$tmp"
    hash -r
    command -v yay >/dev/null || error "yay install failed"
    success "yay installed"
}

install_pacman_packages() {
    section "Official packages (pacman)"
    need_sudo
    local pkgs=(
        hyprland hyprlock hypridle hyprpaper hyprpicker hyprpolkitagent
        waybar swaync nwg-bar brightnessctl
        pipewire-pulse pipewire-alsa pipewire-jack pavucontrol pamixer playerctl
        bluez bluez-utils blueman
        zsh zsh-completions zsh-autosuggestions zsh-syntax-highlighting
        xdg-desktop-portal xdg-desktop-portal-hyprland xdg-desktop-portal-gtk
        grim slurp swappy cliphist wl-clipboard jq imagemagick
        libnotify pacman-contrib
        ttf-jetbrains-mono-nerd otf-font-awesome ttf-fira-code
        network-manager-applet
        base-devel git
        adw-gtk-theme papirus-icon-theme
        lsd fzf
    )
    case "$TERMINAL_CMD" in
        kitty) pkgs+=(kitty) ;;
        alacritty) pkgs+=(alacritty) ;;
        foot) pkgs+=(foot) ;;
        wezterm) pkgs+=(wezterm) ;;
        *) pkgs+=(kitty) ;;
    esac
    case "$BROWSER_CMD" in
        firefox) pkgs+=(firefox) ;;
        chromium) pkgs+=(chromium) ;;
        brave-browser) pkgs+=(brave-browser) ;;
        librewolf) pkgs+=(librewolf) ;;
        *) pkgs+=(firefox) ;;
    esac
    case "$FILE_MANAGER_CMD" in
        thunar) pkgs+=(thunar) ;;
        nautilus) pkgs+=(nautilus) ;;
        dolphin) pkgs+=(dolphin) ;;
        nemo) pkgs+=(nemo) ;;
        pcmanfm) pkgs+=(pcmanfm-gtk3) ;;
        *) pkgs+=(thunar) ;;
    esac
    case "$LAUNCHER_CMD" in
        fuzzel) pkgs+=(fuzzel) ;;
        wofi*) pkgs+=(wofi) ;;
        *) pkgs+=(rofi) ;;
    esac
    [[ "$OPT_BTOP" -eq 1 ]] && pkgs+=(btop fastfetch)
    [[ "$OPT_NWG_LOOK" -eq 1 ]] && pkgs+=(nwg-look)
    [[ "$OPT_NVIDIA" -eq 1 ]] && pkgs+=(linux-headers dkms libva-nvidia-driver)

    sudo pacman -Sy --needed --noconfirm "${pkgs[@]}"
    success "Pacman packages installed"
    fc-cache -f >/dev/null 2>&1 || true
}

install_aur_packages() {
    section "AUR packages (yay)"
    ensure_yay
    local aur=(oh-my-zsh-git zsh-theme-powerlevel10k-git)
    [[ "$OPT_WAYPAPER" -eq 1 ]] && aur+=(waypaper-git)

    # One AUR package failing to build must not take the whole install with
    # it — the configs still need to be linked. Report and carry on.
    local pkg failed=()
    for pkg in "${aur[@]}"; do
        yay -S --needed --noconfirm "$pkg" || failed+=("$pkg")
    done
    if (( ${#failed[@]} )); then
        warn "AUR packages that did not install: ${failed[*]}"
        warn "Install them later with: yay -S ${failed[*]}"
    else
        success "AUR packages installed"
    fi
}

setup_nvidia() {
    [[ "$OPT_NVIDIA" -eq 1 ]] || return 0
    [[ "$NVIDIA_DRIVER" == "none" ]] && return 0

    section "NVIDIA driver"
    need_sudo

    sudo install -Dm644 "$REPO/nvidia/modprobe-nvidia.conf" /etc/modprobe.d/nvidia.conf
    sudo install -Dm644 "$REPO/nvidia/blacklist-nouveau.conf" /etc/modprobe.d/blacklist-nouveau.conf
    sudo install -Dm644 "$REPO/nvidia/modules-load-nvidia.conf" /etc/modules-load.d/nvidia.conf
    success "modprobe / modules-load / nouveau blacklist installed"

    if [[ -f /etc/default/grub ]] && ! grep -q 'nvidia_drm.modeset=1' /etc/default/grub; then
        info "GRUB: adding nvidia_drm.modeset=1 (Arch Wiki NVIDIA / Hyprland)"
        sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 nvidia_drm.modeset=1"/' /etc/default/grub
        sudo grub-mkconfig -o /boot/grub/grub.cfg
        success "GRUB updated"
    fi

    if [[ "$NVIDIA_DRIVER" == "580xx" ]]; then
        info "Removing nvidia-open / conflicting nvidia-utils 590+ ..."
        sudo pacman -Rns --noconfirm nvidia-open nvidia-open-dkms nvidia-open-lts 2>/dev/null || true
        if pacman -Q nvidia-utils &>/dev/null && ! pacman -Q nvidia-580xx-utils &>/dev/null; then
            sudo pacman -Rdd --noconfirm nvidia-utils 2>/dev/null || true
        fi
        ensure_yay
        info "Installing nvidia-580xx-dkms + nvidia-580xx-utils (may take several minutes)..."
        yay -S --needed --noconfirm nvidia-580xx-dkms nvidia-580xx-utils

        info "DKMS: building module for kernel $(uname -r)..."
        # AUR package often leaves status "added" only — force install for current kernel
        if command -v dkms >/dev/null; then
            local ver=""
            ver="$(dkms status 2>/dev/null | awk -F'[/,: ]+' '/^nvidia\//{print $2; exit}')"
            if [[ -n "$ver" ]]; then
                sudo dkms install "nvidia/${ver}" -k "$(uname -r)" 2>/dev/null \
                    || sudo dkms autoinstall \
                    || warn "DKMS install had issues — reboot may still work"
            else
                sudo dkms autoinstall || true
            fi
            dkms status 2>/dev/null || true
        fi
    else
        info "Installing nvidia-open + nvidia-utils from official repos..."
        sudo pacman -S --needed --noconfirm nvidia-open nvidia-utils
    fi

    sudo modprobe nvidia 2>/dev/null || true
    sudo modprobe nvidia_uvm 2>/dev/null || true
    sudo modprobe nvidia_modeset 2>/dev/null || true
    sudo modprobe nvidia_drm 2>/dev/null || true

    if nvidia-smi &>/dev/null; then
        success "nvidia-smi: $(nvidia-smi --query-gpu=name,driver_version --format=csv,noheader)"
    else
        warn "nvidia-smi not ready — reboot required after DKMS (expected on first install)"
    fi
}

backup_and_link() {
    local src="$1" dest="$2"
    mkdir -p "$(dirname "$dest")"
    if [[ -e "$dest" && ! -L "$dest" ]]; then
        mv "$dest" "${dest}.bak.$(date +%s)"
        warn "Backed up: $dest"
    fi
    ln -sf "$src" "$dest"
}

# For files the applications write back into (wallpaper state, waypaper's own
# settings). Symlinking those would have them edit the git checkout.
copy_if_missing() {
    local src="$1" dest="$2"
    mkdir -p "$(dirname "$dest")"
    [[ -L "$dest" ]] && rm -f "$dest"
    [[ -e "$dest" ]] && return 0
    cp "$src" "$dest"
}

# Leftovers from older versions of this repo
clean_stale_links() {
    local stale=(
        "$HOME/.config/hypr/brightness-osd.sh"
        "$HOME/.config/waybar/gpu_stats.sh"
    )
    local f
    for f in "${stale[@]}"; do
        [[ -L "$f" ]] && rm -f "$f" && info "Removed stale link: ${f/#$HOME/\~}"
    done

    # waypaper/config.ini is never overwritten, so a copy made by an earlier
    # version still carries "stylesheet = ~/...". Waypaper is the one path
    # option it does not expand ~ for, and it drops the theme without a word.
    local wp="$HOME/.config/waypaper/config.ini"
    if [[ -f "$wp" && ! -L "$wp" ]] && grep -q '^stylesheet[[:space:]]*=[[:space:]]*~' "$wp"; then
        sed -i '/^stylesheet[[:space:]]*=[[:space:]]*~/d;/^keybindings[[:space:]]*=[[:space:]]*~/d' "$wp"
        info "Removed the unexpandable stylesheet path from waypaper/config.ini"
    fi
    return 0
}

copy_and_patch_hypr() {
    mkdir -p "$(dirname "$HYPR_CONF")"
    if [[ -e "$HYPR_CONF" && ! -L "$HYPR_CONF" ]]; then
        mv "$HYPR_CONF" "${HYPR_CONF}.bak.$(date +%s)"
        warn "Backed up: $HYPR_CONF"
    fi
    cp "$REPO/config/hypr/hyprland.conf" "$HYPR_CONF"
}

# hyprland.conf declares $terminal / $browser / ... once at the top and every
# bind refers to those, so a choice is a single line rewrite.
set_hypr_var() {
    local name="$1" value="$2"
    value="${value//\\/\\\\}"
    value="${value//&/\\&}"
    value="${value//|/\\|}"
    sed -i "s|^[\$]${name} = .*|\$${name} = ${value}|" "$HYPR_CONF"
}

set_hypr_key() {
    local default_key="$1" new_key="$2" var="$3"
    [[ "$default_key" == "$new_key" ]] && return 0
    sed -i "s|^bind = [\$]mainMod, ${default_key}, exec, [\$]${var}\$|bind = \$mainMod, ${new_key}, exec, \$${var}|" "$HYPR_CONF"
}

patch_hyprland_conf() {
    set_hypr_var terminal "$TERMINAL_CMD"
    set_hypr_var browser "$BROWSER_CMD"
    set_hypr_var fileManager "$FILE_MANAGER_CMD"
    set_hypr_var launcher "$LAUNCHER_CMD"

    set_hypr_key T "$KEY_TERMINAL" terminal
    set_hypr_key B "$KEY_BROWSER" browser
    set_hypr_key E "$KEY_FILE_MANAGER" fileManager
    set_hypr_key SPACE "$KEY_LAUNCHER" launcher
    set_hypr_key L "$KEY_LOCK" lockCmd
}

link_configs() {
    section "Linking configs"
    clean_stale_links

    if [[ -f "$HYPR_DEST/hyprland.lua" ]]; then
        mv "$HYPR_DEST/hyprland.lua" "$HYPR_DEST/hyprland.lua.bak.$(date +%s)"
        warn "Moved hyprland.lua aside (Hyprland 0.55+ prefers .lua over .conf)"
    fi

    local f

    # The palette every other config reads
    for f in palette.conf build-theme.sh colors.css colors.rasi colors-kitty.conf colors-hypr.conf; do
        backup_and_link "$REPO/config/theme/$f" "$HOME/.config/theme/$f"
    done

    for f in waybar-autohide.sh osd.sh wallpaper-sync.sh apply-dark-theme.sh hyprlock.conf hypridle.conf; do
        backup_and_link "$REPO/config/hypr/$f" "$HOME/.config/hypr/$f"
    done
    copy_if_missing "$REPO/config/hypr/hyprpaper.conf" "$HOME/.config/hypr/hyprpaper.conf"

    mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
    for f in settings.ini gtk.css; do
        backup_and_link "$REPO/config/gtk-3.0/$f" "$HOME/.config/gtk-3.0/$f"
        backup_and_link "$REPO/config/gtk-4.0/$f" "$HOME/.config/gtk-4.0/$f"
    done
    backup_and_link "$REPO/config/gtk-2.0/.gtkrc-2.0" "$HOME/.gtkrc-2.0"

    mkdir -p "$HOME/.config/waybar/scripts"
    for f in config.jsonc style.css sys_stats.sh; do
        backup_and_link "$REPO/config/waybar/$f" "$HOME/.config/waybar/$f"
    done
    for f in lock-icon.sh lock-toggle.sh; do
        backup_and_link "$REPO/config/waybar/scripts/$f" "$HOME/.config/waybar/scripts/$f"
    done

    backup_and_link "$REPO/config/rofi/config.rasi" "$HOME/.config/rofi/config.rasi"
    backup_and_link "$REPO/config/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"

    for f in config.json style.css; do
        backup_and_link "$REPO/config/swaync/$f" "$HOME/.config/swaync/$f"
    done
    for f in bar.json style.css; do
        backup_and_link "$REPO/config/nwg-bar/$f" "$HOME/.config/nwg-bar/$f"
    done

    backup_and_link "$REPO/config/waypaper/style.css" "$HOME/.config/waypaper/style.css"
    copy_if_missing "$REPO/config/waypaper/config.ini" "$HOME/.config/waypaper/config.ini"

    mkdir -p "$HOME/.local/share/bin"
    for f in launcher-toggle.sh waypaper-toggle.sh session-menu.sh systemupdate.sh; do
        backup_and_link "$REPO/config/local-bin/$f" "$HOME/.local/share/bin/$f"
    done

    backup_and_link "$REPO/zsh/.zshrc" "$HOME/.zshrc"
    backup_and_link "$REPO/bash/.bashrc" "$HOME/.bashrc"

    copy_and_patch_hypr
    patch_hyprland_conf
    success "Configs linked + hyprland.conf patched"
}

set_permissions() {
    chmod +x \
        "$HOME/.config/hypr/"*.sh \
        "$HOME/.config/theme/build-theme.sh" \
        "$HOME/.config/waybar/"*.sh \
        "$HOME/.config/waybar/scripts/"*.sh \
        "$HOME/.local/share/bin/"*.sh \
        "$REPO/nvidia/setup-nvidia.sh" 2>/dev/null || true
    echo "1" > "$HOME/.config/waybar/.pinned"
    # Apply dark theme immediately when gsettings is available
    if [[ -x "$HOME/.config/hypr/apply-dark-theme.sh" ]]; then
        bash "$HOME/.config/hypr/apply-dark-theme.sh" 2>/dev/null || true
    fi
}

setup_default_wallpaper() {
    local wp_dir="$HOME/Wallpapers"
    local wp_file="$wp_dir/default.png"
    mkdir -p "$wp_dir"
    if [[ ! -f "$wp_file" && -f /usr/share/hypr/wall0.png ]]; then
        cp /usr/share/hypr/wall0.png "$wp_file"
        success "Default wallpaper → $wp_file"
    fi
    if [[ -f "$wp_file" ]]; then
        # Resolved path (hyprpaper does not expand ~ reliably)
        cat > "$HOME/.config/hypr/hyprpaper.conf" <<EOF
preload = ${wp_file}
wallpaper = ,contain:${wp_file}
splash = false
EOF
    fi
}

setup_greetd() {
    [[ "$OPT_GREETD" -eq 1 ]] || return 0
    need_sudo
    sudo pacman -S --needed --noconfirm greetd greetd-tuigreet
    [[ -d "$REPO/greetd-config-fix" ]] && sudo cp "$REPO/greetd-config-fix/config.toml" /etc/greetd/config.toml
    sudo systemctl enable greetd
    success "greetd enabled"
}

prompt_interactive() {
    section "Application choices (Enter = default)"
    echo "Terminal: 1) Kitty  2) Alacritty  3) Foot  4) WezTerm"
    read -rp "Choice [1]: " c
    case "${c:-1}" in 2) TERMINAL_CMD=alacritty ;; 3) TERMINAL_CMD=foot ;; 4) TERMINAL_CMD=wezterm ;; *) TERMINAL_CMD=kitty ;; esac
    echo "Browser: 1) Firefox  2) Chromium  3) Brave  4) Librewolf"
    read -rp "Choice [1]: " c
    case "${c:-1}" in 2) BROWSER_CMD=chromium ;; 3) BROWSER_CMD=brave-browser ;; 4) BROWSER_CMD=librewolf ;; *) BROWSER_CMD=firefox ;; esac
    echo "File manager: 1) Thunar  2) Nautilus  3) Dolphin  4) Nemo  5) PCManFM"
    read -rp "Choice [1]: " c
    case "${c:-1}" in 2) FILE_MANAGER_CMD=nautilus ;; 3) FILE_MANAGER_CMD=dolphin ;; 4) FILE_MANAGER_CMD=nemo ;; 5) FILE_MANAGER_CMD=pcmanfm ;; *) FILE_MANAGER_CMD=thunar ;; esac
    echo "Launcher: 1) Rofi  2) Fuzzel  3) Wofi"
    read -rp "Choice [1]: " c
    # shellcheck disable=SC2088  # tilde is expanded by Hyprland, not the shell
    case "${c:-1}" in 2) LAUNCHER_CMD=fuzzel ;; 3) LAUNCHER_CMD="wofi --show drun" ;; *) LAUNCHER_CMD="~/.local/share/bin/launcher-toggle.sh" ;; esac
    read -rp "Waypaper (AUR)? [Y/n]: " c; [[ "${c,,}" == "n" ]] && OPT_WAYPAPER=0
    read -rp "Btop? [Y/n]: " c; [[ "${c,,}" == "n" ]] && OPT_BTOP=0
    read -rp "greetd + tuigreet? [y/N]: " c; [[ "${c,,}" == "y" ]] && OPT_GREETD=1
    read -rp "nwg-look? [Y/n]: " c; [[ "${c,,}" == "n" ]] && OPT_NWG_LOOK=0
    read -rp "Use default shortcuts (Super+T/B/E/Space/L)? [Y/n]: " c
    if [[ "${c,,}" == "n" ]]; then
        read -rp "Terminal key [T]: " KEY_TERMINAL; KEY_TERMINAL=${KEY_TERMINAL:-T}
        read -rp "Browser key [B]: " KEY_BROWSER; KEY_BROWSER=${KEY_BROWSER:-B}
        read -rp "File manager key [E]: " KEY_FILE_MANAGER; KEY_FILE_MANAGER=${KEY_FILE_MANAGER:-E}
        read -rp "Launcher key [SPACE]: " KEY_LAUNCHER; KEY_LAUNCHER=${KEY_LAUNCHER:-SPACE}
        read -rp "Lock key [L]: " KEY_LOCK; KEY_LOCK=${KEY_LOCK:-L}
    fi
}

print_plan() {
    section "Install plan"
    echo "  Mode:          $MODE"
    echo "  Terminal:      $TERMINAL_CMD  (Super+$KEY_TERMINAL)"
    echo "  Browser:       $BROWSER_CMD  (Super+$KEY_BROWSER)"
    echo "  File manager:  $FILE_MANAGER_CMD  (Super+$KEY_FILE_MANAGER)"
    echo "  Launcher:      $LAUNCHER_CMD"
    echo "  Waypaper: $OPT_WAYPAPER | Btop: $OPT_BTOP | nwg-look: $OPT_NWG_LOOK | greetd: $OPT_GREETD"
    echo "  NVIDIA:        $NVIDIA_DRIVER"
    echo ""
}

run_full_install() {
    install_pacman_packages
    install_aur_packages
    setup_nvidia
    setup_greetd
    link_configs
    set_permissions
    setup_default_wallpaper
}

# --- main ---
parse_args "${1:-}"
banner "StxSaryus Arch Hyprland Dotfiles"
print_official_notices
detect_gpu

case "$MODE" in
    interactive)
        prompt_interactive
        print_plan
        read -rp "Proceed? [Y/n]: " c
        [[ "${c,,}" == "n" ]] && exit 0
        run_full_install
        ;;
    auto)
        print_plan
        if [[ "$SKIP_CONFIRM" -eq 0 ]]; then
            read -rp "Install everything with defaults above? [Y/n]: " c
            [[ "${c,,}" == "n" ]] && { info "Aborted. Use --interactive to customize."; exit 0; }
        fi
        run_full_install
        ;;
    configs)
        link_configs
        set_permissions
        setup_default_wallpaper
        ;;
    packages)
        install_pacman_packages
        install_aur_packages
        setup_nvidia
        setup_greetd
        ;;
esac

banner "Installation complete"
echo -e "${GREEN}${BOLD}Next steps:${NC}"
echo "  1) ${BOLD}sudo reboot${NC}   ← required for NVIDIA DKMS / modules"
echo "  2) After login:  nvidia-smi"
echo "  3) Super+T terminal | Super+B browser | Super+E files | Super+Space launcher"
echo ""
echo -e "${DIM}Docs: INSTALL.md${NC}"
echo -e "${DIM}NVIDIA Pascal: Arch News → nvidia-580xx-dkms (AUR)${NC}"
echo ""
