#!/usr/bin/env bash
#
# Generates every per-application colour file from config/theme/palette.conf.
#
#   ./build-theme.sh          regenerate the colour files
#   ./build-theme.sh --check  fail if the committed files are out of date
#
set -euo pipefail

# shellcheck source-path=SCRIPTDIR
THEME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PALETTE="$THEME_DIR/palette.conf"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# shellcheck source=palette.conf
source "$PALETTE"

HEADER_NOTE="Generated by config/theme/build-theme.sh from palette.conf — do not edit."

# --- colour helpers -----------------------------------------------------
rgb_parts() { printf '%d %d %d' "0x${1:0:2}" "0x${1:2:2}" "0x${1:4:2}"; }

# hex + alpha (0.00-1.00) -> "rgba(r, g, b, a)"
css_rgba() {
    local r g b
    read -r r g b <<<"$(rgb_parts "$1")"
    printf 'rgba(%d, %d, %d, %s)' "$r" "$g" "$b" "$2"
}

# hex + alpha (0.00-1.00) -> "#rrggbbaa"
hex_rgba() {
    local a
    a=$(awk -v x="$2" 'BEGIN { printf "%02x", int(x * 255 + 0.5) }')
    printf '#%s%s' "$1" "$a"
}

# blend a colour towards white by a 0.00-1.00 factor
lighten() {
    local r g b
    read -r r g b <<<"$(rgb_parts "$1")"
    awk -v r="$r" -v g="$g" -v b="$b" -v f="$2" \
        'BEGIN { printf "%02x%02x%02x", r+(255-r)*f, g+(255-g)*f, b+(255-b)*f }'
}

# --- derived tokens -----------------------------------------------------
bright_red=$(lighten "$red" 0.18)
bright_green=$(lighten "$green" 0.18)
bright_yellow=$(lighten "$yellow" 0.18)
bright_blue=$(lighten "$blue" 0.18)

write() {
    local target="$1" tmp
    tmp="$(mktemp)"
    cat >"$tmp"
    if (( CHECK )); then
        if ! diff -q "$target" "$tmp" >/dev/null 2>&1; then
            echo "OUT OF DATE: ${target#"$THEME_DIR"/}  (run config/theme/build-theme.sh)" >&2
            diff -u "$target" "$tmp" | head -40 >&2 || true
            rm -f "$tmp"
            return 1
        fi
        rm -f "$tmp"
    else
        mv "$tmp" "$target"
        echo "  wrote ${target#"$THEME_DIR"/}"
    fi
}

# --- GTK CSS (waybar, swaync, nwg-bar, waypaper, gtk3/gtk4) -------------
write "$THEME_DIR/colors.css" <<EOF
/* $HEADER_NOTE */

@define-color crust   #$crust;
@define-color base    #$base;
@define-color mantle  #$mantle;
@define-color surface #$surface;
@define-color overlay #$overlay;
@define-color line    #$line;

@define-color text    #$text;
@define-color subtext #$subtext;
@define-color muted   #$muted;
@define-color faint   #$faint;

@define-color accent      #$accent;
@define-color accent_deep #$accent_deep;
@define-color blue        #$blue;
@define-color mauve       #$mauve;
@define-color green       #$green;
@define-color teal        #$teal;
@define-color yellow      #$yellow;
@define-color peach       #$peach;
@define-color red         #$red;
@define-color pink        #$pink;

/* translucent surfaces */
@define-color bar_bg    $(css_rgba "$mantle" "$alpha_bar");
@define-color popup_bg  $(css_rgba "$base" "$alpha_popup");
@define-color card_bg   $(css_rgba "$surface" "$alpha_card");
@define-color hover_bg  $(css_rgba "$overlay" "$alpha_hover");
@define-color dim_bg    $(css_rgba "$crust" "0.55");

/* tinted states */
@define-color accent_soft $(css_rgba "$accent" "0.16");
@define-color red_soft    $(css_rgba "$red" "0.16");
@define-color green_soft  $(css_rgba "$green" "0.16");
@define-color hairline    $(css_rgba "$line" "0.55");
@define-color shadow      rgba(0, 0, 0, 0.45);
EOF

# --- Rofi ---------------------------------------------------------------
write "$THEME_DIR/colors.rasi" <<EOF
/* $HEADER_NOTE */

* {
    crust:   #$crust;
    base:    #$base;
    mantle:  #$mantle;
    surface: #$surface;
    overlay: #$overlay;
    line:    #$line;

    text:    #$text;
    subtext: #$subtext;
    muted:   #$muted;
    faint:   #$faint;

    accent:      #$accent;
    accent-deep: #$accent_deep;
    green:       #$green;
    yellow:      #$yellow;
    red:         #$red;

    popup-bg:    $(hex_rgba "$base" "$alpha_popup");
    card-bg:     $(hex_rgba "$surface" "$alpha_card");
    hover-bg:    $(hex_rgba "$overlay" "$alpha_hover");
    accent-soft: $(hex_rgba "$accent" "0.16");

    radius-sm: 8px;
    radius-md: 12px;
    radius-lg: 16px;
}
EOF

# --- Kitty --------------------------------------------------------------
write "$THEME_DIR/colors-kitty.conf" <<EOF
# $HEADER_NOTE

background_opacity    $alpha_term

foreground            #$text
background            #$base
selection_foreground  #$crust
selection_background  #$accent
cursor                #$accent
cursor_text_color     #$crust
url_color             #$accent

active_border_color   #$accent
inactive_border_color #$line
bell_border_color     #$peach

active_tab_foreground   #$crust
active_tab_background   #$accent
inactive_tab_foreground #$muted
inactive_tab_background #$surface
tab_bar_background      #$mantle

# black
color0  #$faint
color8  #$muted
# red
color1  #$red
color9  #$bright_red
# green
color2  #$green
color10 #$bright_green
# yellow
color3  #$yellow
color11 #$bright_yellow
# blue
color4  #$blue
color12 #$bright_blue
# magenta
color5  #$mauve
color13 #$pink
# cyan
color6  #$teal
color14 #$accent
# white
color7  #$subtext
color15 #$text
EOF

# --- Hyprland / Hyprlock ------------------------------------------------
write "$THEME_DIR/colors-hypr.conf" <<EOF
# $HEADER_NOTE

\$crust   = rgb($crust)
\$base    = rgb($base)
\$mantle  = rgb($mantle)
\$surface = rgb($surface)
\$overlay = rgb($overlay)
\$line    = rgb($line)

\$text    = rgb($text)
\$subtext = rgb($subtext)
\$muted   = rgb($muted)
\$faint   = rgb($faint)

\$accent  = rgb($accent)
\$accentDeep = rgb($accent_deep)
\$green   = rgb($green)
\$yellow  = rgb($yellow)
\$red     = rgb($red)

# border / surface variants with alpha
\$borderActive   = rgba(${accent}ee)
\$borderInactive = rgba(${line}aa)
\$lockBg         = rgba(${crust}f2)
\$lockField      = rgba(${surface}cc)
\$lockShadow     = rgba(00000066)
EOF

if (( CHECK )); then
    echo "theme files are in sync with palette.conf"
else
    echo "theme rebuilt from $(basename "$PALETTE")"
fi
